### ISSUE TITLE
Appendix H not reproducible of Book "Intro to GIS and Spatial Analysis"

### ISSUE THREAD

**Issue by martial00120** [mgimond/Spatial#5]
Hello! I like your book "Intro to GIS and Spatial Analysis" very much.
However the files in Appendix H are not reproducible:
https://mgimond.github.io/Spatial/point-pattern-analysis-in-r.html

For example: the "MA.shp" files is missing in the "data" folder on your repo. Would you like to check it?

**Comment by mgimond** [comment]
This code chunk has  sown confusion for some readers. Its original intent was to show how one could load shapefiles (without actually doing so in the appendix). That is what was meant in the paragraph leading up to the code: 

>  "The [first appendix](https://mgimond.github.io/Spatial/reading-and-writing-spatial-data-in-r.html#converting-an-sf-point-object-to-a-ppp-object) steps you through the process of loading external data into R. But in summary, if you had layers stored as shapefile and raster file formats, you could import the data using the following example:"

This will be removed from the appendix  since it does not contribute to the appendix workflow. Anyone wanting to see a PPA workflow that includes loading shapefiles from scratch may point to https://mgimond.github.io/es214_support_tutorials/

**Comment by mgimond** [comment]
Commit d66135ece671cb8d74995875525286a37651ab6e resolves this issue.
